### ISSUE TITLE
Evaluation using pre-trained .npz file 

### ISSUE THREAD

**Issue by Prudvi01** [SeitaroShinagawa/chainer-partial_convolution_image_inpainting#31]
Hello @SeitaroShinagawa I don't have an Nvidia GPU so I'm using CPU by excluding (-g 0) but running the command 'python generete_result.py --load_model model500000.npz' still says shows the following error
![Screenshot 2019-08-23 at 6 30 44 PM](https://user-images.githubusercontent.com/29304096/63594497-32f27580-c5d4-11e9-94f5-7773bd91c993.jpg)

# update
I tried it on google colab with GPU on and received this error
![Screenshot 2019-08-24 at 7 59 43 PM](https://user-images.githubusercontent.com/29304096/63638731-baf67f00-c6a9-11e9-99b6-cf90eff581d3.jpg)

_Originally posted by @Prudvi01 in https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/issues/2#issuecomment-524307005_

**Comment by Prudvi01** [comment]
[Continuing from this comment](https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/issues/32#issuecomment-524804871), could you please help me with this issue @SeitaroShinagawa

**Comment by SeitaroShinagawa** [comment]
See [here](https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/generate_result.py#L22). To run with CPU, you need prefix `-g -1`, for example.  

Sorry I'm not familiar with colab, but the error seems to be derived from data loading issue as well.

**Comment by Prudvi01** [comment]
Hello, thank you that worked but ran into some other weird issue. I say weird because running the same command gives me 2 different errors each alternative times. Can you please help me with this?
![Screenshot 2019-09-01 at 8 51 12 AM](https://user-images.githubusercontent.com/29304096/64071365-7749d980-cc96-11e9-9ca1-61f757459d89.jpg)
