### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by Prudvi01** [SeitaroShinagawa/chainer-partial_convolution_image_inpainting#32]
I followed the suggestions in this [thread](https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/issues/7) but still ran into the same issue but that issue was closed so had to open a new one. I changed my path and double-checked. I used a small dataset the "Small images (256 * 256) with easy directory structure" 21G one. It only has the train and val data set so I copied the val data and named it train_256. 
Can you please help me with the dataset structure?
![Screenshot 2019-08-21 at 11 15 09 PM](https://user-images.githubusercontent.com/29304096/63455707-eb040f00-c46a-11e9-8747-27c8e95dd5a9.jpg)
![Screenshot 2019-08-21 at 11 25 47 PM](https://user-images.githubusercontent.com/29304096/63455750-03742980-c46b-11e9-9d64-73a1ca503393.jpg)
![Screenshot 2019-08-21 at 11 26 19 PM](https://user-images.githubusercontent.com/29304096/63455795-1686f980-c46b-11e9-99fe-58c1afd049f2.jpg)

# UPDATE: I changed my dataset paths to a different location and now running this
#to check train data path
>>> import glob
>>> from common import paths
>>> train_keys = glob.glob(paths.train_place2+"*/*/*.jpg")
>>> print(len(train_keys))
#if successful, you will get "1434892" as return

returns 1803460, I assume thats because of the different dataset but that's better than 0 which I used to get before. But the ZeroDivisionError: division by zero error persists. Can you please help?

_Originally posted by @Prudvi01 in https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/issues/7#issuecomment-523578798_

**Comment by SeitaroShinagawa** [comment]
Have you checked your paths.py is correct? It seems that you forgot "/" at the end of each path.
```
#common/paths.py
train_place2 = "/yourpath/place2/data_256/"
val_place2 = "/yourpath/place2/val_256/"
test_place2 = "/yourpath/test_256/"
```

**Comment by Prudvi01** [comment]
I just tried with '/' at the end and still ran into the same problem...

**Comment by SeitaroShinagawa** [comment]
"`print(len(train_keys))` is zero" means you failed to load images. In most of this case, the link of paths.py is wrong.  
Could you show me the actual absolute link of your dataset?

**Comment by SeitaroShinagawa** [comment]
I mean I want to see the result of the following commands if you use linux.
```
cd your/dataset/path
pwd
```

**Comment by Prudvi01** [comment]
This is the path I'm getting which is exactly what I've entered
![Screenshot 2019-08-24 at 10 05 35 PM](https://user-images.githubusercontent.com/29304096/63640228-4e847b80-c6bb-11e9-9030-3e1bb194801c.jpg)
![Screenshot 2019-08-24 at 10 06 35 PM](https://user-images.githubusercontent.com/29304096/63640239-7247c180-c6bb-11e9-9219-53916e9505a6.jpg)

**Comment by Prudvi01** [comment]
I'd like to point that this issue seems to be different from [https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/issues/7#issuecomment-396147682](this) issue because in my case it says self._epoch_size instead of length in the denominator.
![Screenshot 2019-08-24 at 10 44 19 PM](https://user-images.githubusercontent.com/29304096/63640679-b8535400-c6c0-11e9-9543-cd59de5fcc2a.jpg)

**Comment by SeitaroShinagawa** [comment]
Please check where self._epoch_size is defined.  
https://github.com/chainer/chainer/blob/34655eff5986522eae56f47fc82a8cc2b78e1617/chainer/iterators/multiprocess_iterator.py#L261
![image](https://user-images.githubusercontent.com/7993233/63646553-cd2af880-c74f-11e9-8f0c-e4305108d893.png)
self._eoch_size becomes zero if you start a new training and you failed to load images. It means this issue happens for the same reason.

Is your path, `Downloads/Projects` correct? I think this part should be the lowercase `downloads/projects`.

**Comment by Prudvi01** [comment]
Thank you for the reply I tried lowercase too, still same error. Can you please share exactly which version of place2 dataset you've downloaded and it's directory?

**Comment by SeitaroShinagawa** [comment]
Oh, I see. I don't use "Small images (256 * 256) with easy directory structure 21GB", but "Small images (256 * 256) 24GB" one. That's why you failed to load. 
```
place2
├── data_256
│   ├── a
│   │   ├── airfield
│   │   │   ├── 00000001.jpg
│   │   │   ├── 00000002.jpg
```
The directory structure I supposed is like this.

**Comment by Prudvi01** [comment]
I downloaded the same dataset as yours and thankfully it didn't throw that error. I assume it's training now(it's showing nothing after loading the vgg16 and 'ok" output), how long can I expect for it to take for training? I don't have GPU so I've excluded (-g 0) option. I suppose it'll take a long time, so can you please help me with this other issue when I try to use your trained model500000.npz for evaluation but it says "CUDA environment not set up correctly". Thank you again for being so patient.
