### ISSUE TITLE
Where can I set VGG.caffemodel ?

### ISSUE THREAD

**Issue by jeejeeli** [SeitaroShinagawa/chainer-partial_convolution_image_inpainting#4]
Hi ,
I downloaded the VGG_ILSVRC_16_layers.caffemodel manually ,But I don't know where can I set this model? can you tell me ,thanks ~~~

**Comment by SeitaroShinagawa** [comment]
Hi @jeejeeli,   

Thanks for your interest. Actually, you don't need to download it manually. Chainer supports auto-downloading via chainer.links.VGG16Layers. See below,   https://docs.chainer.org/en/stable/reference/generated/chainer.links.VGG16Layers.html  

Of course, you can use your manually-downloaded model using chainer.links.VGG16Layers. See below,  
https://github.com/chainer/chainer/blob/master/chainer/links/model/vision/vgg.py#L114   
"pretrained_model" denotes your model path.  

Here is an actual usage.  
```python
from chainer.links import VGG16Layers

#Default
model = VGG16Layers()

#To use your model
model = VGG16Layers(pretrained_model="path_to_your_model")
```
I hope this instruction helps you!  
Best,

**Comment by jeejeeli** [comment]
Hi @SeitaroShinagawa ,
Thanks your reply,Because  Chainer auto -downloading  is very slow in my PC ,so I downloaded VGG.caffemodel by hand,  I using your recommend instructions 
    ## vgg = VGG16Layers(pretrained_model="/mountData/VGG_ILSVRC_16_layers.caffemodel")
    the error as follow:    
## OSError: Failed to interpret file '/mountData/VGG_ILSVRC_16_layers.caffemodel' as a pickle
I am a rookie for Chainer ,I hope you can help me ,Thanks very much
Best wishes to you

**Comment by jeejeeli** [comment]
I have sloved this problem ,frist I using the function "convert_caffemodel_to_npz " convert vgg.caffemodel to vgg.pkl, then I use your recommend instrcution ,Thanks very much
