### ISSUE TITLE
where is the upsampling

### ISSUE THREAD

**Issue by lipanpeng** [SeitaroShinagawa/chainer-partial_convolution_image_inpainting#5]
Excuse me! I'm new to the chainer framework. In your code, I found the convolution operation with the class PConv. But I can't find how you implement upsampling. Can you point it out for me?

**Comment by SeitaroShinagawa** [comment]
Hi @lipanpeng,  

Thanks for your interest and sorry for confusing you. Upsampling part is outside of PConv. See below,  
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/common/net.py#L197   

Class "PartialConvCompletion" is the whole network. It calls upsampling after PConv in generater part.   
Note that I actually used chainer.functions.unpooling_2d as upsampling. You can replace it with  chainer.functions.upsampling_2d if you want more precise implementation for the original paper.    
https://docs.chainer.org/en/stable/reference/generated/chainer.functions.upsampling_2d.html#chainer-functions-upsampling-2d

**Comment by lipanpeng** [comment]
Thanks for your explanation. Your code help me a lot to get through the paper.

**Comment by lipanpeng** [comment]
Sorry to bother you again! I have a problem about the mask. Is the channel of original mask 1? And how do you process the mask of which the channel become double after concatenate the mask from unpooling and the one from encoder?

**Comment by SeitaroShinagawa** [comment]
@lipanpeng Yes, the channel of mask iterated from dataloader is originally 1, but it is broadcast to 3 as below,
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/updater.py#L121
```python
batch = self.get_iterator('main').next()
mask_train = np.zeros((batchsize, 3, w_in, w_in)).astype("f")
for i in range(batchsize):
    mask_train[i, :] = batch[i][1] # mask channel is broadcast from 1 to 3
```
Do you mean the decorder part in the second question? I concatenate the mask from unpooling and the one from encoder along with channel axis like this, 
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/common/net.py#L203

**Comment by lipanpeng** [comment]
@SeitaroShinagawa Is the channel of mask same with the channel of features? If not, how to do the element-wise multiplication of features and masks?

**Comment by SeitaroShinagawa** [comment]
@lipanpeng Yes, the channel of mask is same to the channel of features.

**Comment by SeitaroShinagawa** [comment]
@lipanpeng See updater.py,
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/updater.py
calc_loss_perceptual, calc_loss_style, and calc_loss_tv represents perceptual, style, and tv loss, respectively.   

Valid and hole loss is defined here,
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/updater.py#L144

As you can see, I use mean in these losses.  
Best,

**Comment by lipanpeng** [comment]
@SeitaroShinagawa OK! Thanks a lot for your patience!
