### ISSUE TITLE
The error "divsion by zero"

### ISSUE THREAD

**Issue by sunnydai** [SeitaroShinagawa/chainer-partial_convolution_image_inpainting#7]
Excuse me! I'm new to the chainer framework and python. When i train with the command "python train.py",  it always occur the error ''divsion by zero', i am confused! Hope your responce

**Comment by SeitaroShinagawa** [comment]
Hi @sunnydai,  
Thanks for your report. Could you show me the actual error you have observed?

**Comment by sunnydai** [comment]
Thank you for your responce, the error is as follow!
![qq 20180611145835](https://user-images.githubusercontent.com/21050211/41216766-3fc48bf4-6d88-11e8-996a-2502969e0375.jpg)

**Comment by sunnydai** [comment]
I have set my own datasets path. But my datasets is not as large as the original one, I just select some of the pictures and i use 'python train.py' instead of 'python train.py -g 0'. I don't know if these two changes make the error?


![qq 20180611153334](https://user-images.githubusercontent.com/21050211/41218260-11fe137a-6d8d-11e8-8966-53e3d2a61190.png)

**Comment by SeitaroShinagawa** [comment]
Option -g means the gpu id you want to use as below,  
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/train.py#L22  
There is no relationship between -g and loading dataset.    

Is your mask dataset which is generated by generate_windows.py also correct?  
Default train.py uses image size of 256 as below,  
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/train.py#L92
```python
#actual command to generate mask dataset
python generate_windows.py 256 1000
```

**Comment by sunnydai** [comment]
Yes, I have generate the mask. 
![qq 20180611160845](https://user-images.githubusercontent.com/21050211/41219780-f98a146a-6d91-11e8-96dd-4ed90d13f544.png)

**Comment by sunnydai** [comment]
It maybe the failure of the loading of VGG model because the 'completing model loaded' is missed. And i find that the VGG model has been download, I don't konw why the error occur?

**Comment by SeitaroShinagawa** [comment]
Actually, 'Completion model' represents the trained model with this completion (in-painting) network, not the VGG model. It has been successful because you got 'ok' in the line of 64.

**Comment by sunnydai** [comment]
Oh~In ‘train.py’ line 92, mask_path=''mask/256", if it should be mask_path=''mask/256/"?

**Comment by SeitaroShinagawa** [comment]
Let me confirm your path is correct again. Could you run the following commands?   
```
#to check train data path
>>> import glob
>>> from common import paths
>>> train_keys = glob.glob(paths.train_place2+"*/*/*.jpg")
>>> print(len(train_keys))
# if successful, you will get "1434892" as return
```

```
#to check mask path
>>> import glob
>>> from common import paths
>>> mask_keys = glob.glob("mask/256/*.bmp")
>>> print(len(mask_keys))
# if successful, you will get "1000" as return
```

**Comment by SeitaroShinagawa** [comment]
mask_path=''mask/256" is correct. See here,
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/datasets/place2.py#L20
(Sorry for confusing you, the comment in this line is my mistake.)

**Comment by sunnydai** [comment]
Thanks for your patience! I have find the question. I make a mistake in "place2.py"~

**Comment by sunnydai** [comment]
Another error occur when i am training, when the evaluation process is needed, there is an error 'numpy.ndarray' object has no attribute 'get'
![qq 20180612214937](https://user-images.githubusercontent.com/21050211/41294516-cba46bfa-6e8a-11e8-8390-8943f971dbc1.png)

**Comment by SeitaroShinagawa** [comment]
Sorry for the inconvenience. It seems that you executed the code with CPU mode, right?  
"get" changes a cuda.array to numpy.array.  
You can solve it by removing .get() in this case.

**Comment by sunnydai** [comment]
Thank you very much! It is ok now!

**Comment by sunnydai** [comment]
I am sorry to trouble you again. After training the model, when i execute the "generate_result.py", I can not load the model that i have trained. The model are saved in "result".
![qq 20180618145046](https://user-images.githubusercontent.com/21050211/41522174-89d93e7c-7307-11e8-9aae-c73ac339f45d.jpg)
![qq 20180618145055](https://user-images.githubusercontent.com/21050211/41522183-8ff1f8a8-7307-11e8-8e43-8320b3e27810.jpg)

**Comment by SeitaroShinagawa** [comment]
generate_result.py requires model path option, "--load_model" as below,  
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/generate_result.py#L26
```
#example
python gnerate_result.py -g 0 --load_model your/model/path
```

**Comment by sunnydai** [comment]
Thank you very much~

**Comment by Prudvi01** [comment]
@sunnydai thank you for this thread. I followed the suggestions in this thread but still ran into the same issue. I changed my path and double checked. I used a small dataset the "Small images (256 * 256) with easy directory structure" 21G one. It only has the train and val data set so I copied the val data and named it train_256. 
Can you please help me with the dataset structure?
![Screenshot 2019-08-21 at 11 15 09 PM](https://user-images.githubusercontent.com/29304096/63455707-eb040f00-c46a-11e9-8747-27c8e95dd5a9.jpg)
![Screenshot 2019-08-21 at 11 25 47 PM](https://user-images.githubusercontent.com/29304096/63455750-03742980-c46b-11e9-9d64-73a1ca503393.jpg)
![Screenshot 2019-08-21 at 11 26 19 PM](https://user-images.githubusercontent.com/29304096/63455795-1686f980-c46b-11e9-99fe-58c1afd049f2.jpg)
