### ISSUE TITLE
The error Unsupported dtype object

### ISSUE THREAD

**Issue by yuzhesu** [SeitaroShinagawa/chainer-partial_convolution_image_inpainting#8]
when I run the  generate_result.py ,and set up correct, it appear The error Unsupported dtype object! How can I solve this problem?
![1528703606615](https://user-images.githubusercontent.com/40162993/41219327-8808a1ea-6d90-11e8-8d2f-d1440cc48a99.jpg)

**Comment by SeitaroShinagawa** [comment]
Thanks for your report.   
Could you check batch[i][1] in line 111 by "print(type(batch[i][1]))"?  
It should be a numpy array, but it seems None in your case.  
If it is None, check whether the dataset path and mask dataset path is correct or not.

**Comment by yuzhesu** [comment]
I have already change test_place2 in Edit common/paths.py 
But when I run the generate_result.py , I still can't get the test pictures, If I want to get the test pictures, Where should I set the path?

**Comment by SeitaroShinagawa** [comment]
You don't need use test_dataset.
This is a simple example to load dataset. Could you try to execute the following code?
```
#!/usr/bin/env python

import datasets
from common import paths

val_dataset = getattr(datasets, "place2_test")(paths.val_place2, mask_path="mask/256", resize_to=256, crop_to=256)
val_iter = chainer.iterators.SerialIterator(val_dataset, 1)
batch = val_iter.next()

print(type(batch[0][1]))
#correct return --> <class 'numpy.ndarray'>
```

**Comment by yuzhesu** [comment]
When I  execute the following code, it show <class 'NoneType'>
How can I solve this problem？

**Comment by SeitaroShinagawa** [comment]
There are 2 possibilities, paths.val_place2 is wrong or mask_path is wrong.  
Judging from your case, loading mask has failed.  
Could you show the result of "ls" and "ls mask" command in the root directory of this repository?

**Comment by yuzhesu** [comment]
I think paths.val_place2 is setting correct.
Where can mask_path be set？
Sorry, what is "ls" and "ls mask" meaning  for?

**Comment by SeitaroShinagawa** [comment]
Sorry, I want to see where is your mask path.   
If your mask path is correct, you can do the following commands:  
```
>>> import glob
>>> maskkeys = glob.glob("mask/256/*.bmp")
>>> print(maskkeys)
['mask/256/mask_256_00.bmp', 'mask/256/mask_256_07.bmp', 'mask/256/mask_256_09.bmp', 'mask/256/mask_256_08.bmp', 'mask/256/mask_256_06.bmp', 'mask/256/mask_256_01.bmp', 'mask/256/mask_256_02.bmp', 'mask/256/mask_256_05.bmp', 'mask/256/mask_256_04.bmp', 'mask/256/mask_256_03.bmp']
```
Could you try this?

**Comment by yuzhesu** [comment]
![1528725177543](https://user-images.githubusercontent.com/40162993/41235746-016ec9e8-6dc2-11e8-8b8b-ecf7e365b272.jpg)
Here!

**Comment by SeitaroShinagawa** [comment]
Oh, I think glob has some problem with windows.  
Can you load the mask from the paths?  For example,
```
from PIL import Image
img = Image.open(maskkeys[0])
```

**Comment by SeitaroShinagawa** [comment]
"mask/256*.bmp" is not a list but string.  I mean you should try
```
>>> import glob
>>> from PIL import Image
>>> maskkeys = glob.glob("mask/256/*.bmp")
>>> img = Image.open(maskkeys[0])
```
Does it work?

**Comment by yuzhesu** [comment]
Yes, it can work.
![1528731563091](https://user-images.githubusercontent.com/40162993/41241983-f1d35472-6dd0-11e8-9531-787b027b41ac.jpg)
So how do I generate the result correctly？
Thanks

**Comment by SeitaroShinagawa** [comment]
I suppose cv2.imread has something wrong in your environment.  
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/datasets/place2.py#L109

Could you try to replace this line as follows?
```
#mask = cv2.imread(idM, cv2.IMREAD_GRAYSCALE)
mask = np.array(Image.open(idM)).astype("f")
```
However, I wonder why you can excecute train.py if cv2.imread is the cause...

**Comment by yuzhesu** [comment]
I have already replace this line as follows, but it still have error
![1528733780664](https://user-images.githubusercontent.com/40162993/41244009-62eafa20-6dd6-11e8-980f-e1d8e81169d6.jpg)
Because I didn't perform train.py , I directly download model500000.npz to execute generate_result.py.

**Comment by SeitaroShinagawa** [comment]
The error occurred in loading mask from  your mask path "idM."  
Surprisingly, idM has become changed to 'C:\Users\La' in your case.  
Could you try "print(idM)" before the line 110 in place2.py?

**Comment by yuzhesu** [comment]
I have already "print(idM)" before the line 110 in place2.py, Show the same result 'C:\Users\La'.
![1528780698404](https://user-images.githubusercontent.com/40162993/41271439-3da1d546-6e43-11e8-81b4-008c46a4b384.jpg)
How can I solve it?

**Comment by SeitaroShinagawa** [comment]
Umm, can you do "print(self.maskkey)" before the line 110? It seems the cause you have.

**Comment by yuzhesu** [comment]
![1528785975752](https://user-images.githubusercontent.com/40162993/41274190-23f5de24-6e4f-11e8-935f-851e83ccf310.jpg)
Here!

**Comment by SeitaroShinagawa** [comment]
I have fixed it (remove [:len(self.trainAkey)]) and it works.   

https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/commit/ad4048bc46b5b49141da9e5c9a9970c560bae7b4#diff-ab9bbf0e02017a0e3d0a81a64530a22eR98  

Thank you for your patience!

**Comment by yuzhesu** [comment]
Yes, I have already remove it, the result is
![1528793944059](https://user-images.githubusercontent.com/40162993/41280511-b2800374-6e61-11e8-92f6-a20647c67179.jpg)
If I remove [:len(self.trainAkey)] results will have an impact?
Thank you for your answer patiently.

**Comment by yuzhesu** [comment]
Sorry I have another question, If I want to get the Input result like this
![1528794847688](https://user-images.githubusercontent.com/40162993/41281359-c02a26c4-6e63-11e8-8cd0-6b8c0a378ab0.jpg)
How can I set?

**Comment by SeitaroShinagawa** [comment]
You want to get 1 image, is it correct?  
Change the input of "batch_postprocess_images"
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/generate_result.py#L92   
Best,

**Comment by SeitaroShinagawa** [comment]
My implementation does not support it. However, you can do it by replacing the mask part value with 1.0 on each channel.  

You can do like here,  
https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/generate_result.py#L88

```
#easiest way
output_image = F.where(M_b, I_gt, Variable(xp.ones((batchsize, 3, image_size, image_size)).astype("f"))
```

**Comment by yuzhesu** [comment]
I understand!Thank you for your answer patiently.
