### ISSUE TITLE
about prepocessing

### ISSUE THREAD

**Issue by syan1992** [SeitaroShinagawa/chainer-partial_convolution_image_inpainting#9]
Are there any differences between x/127.5-1 and x/255?

**Comment by SeitaroShinagawa** [comment]
Hi,
The former rescales [0, 255] to [-1, 1], the latter rescales to [0, 1].

**Comment by syan1992** [comment]
@SeitaroShinagawa Aha, I don't know what I was thinking at that time. Many thanks.
